# Generated by Django 2.1.3 on 2018-12-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age', models.PositiveIntegerField()),
                ('checkin', models.DateTimeField(auto_now=True)),
                ('phoneno', models.PositiveIntegerField()),
                ('idproof', models.ImageField(upload_to='')),
                ('room', models.CharField(choices=[('Normal', 'NORMAL'), ('Ac', 'AC'), ('Non-ac', 'NON-AC'), ('Delux', 'DELUX'), ('Delux Pro', 'DELUX PRO'), ('Super Delux', 'SUPER DELUX'), ('Suite', 'SUITE')], max_length=25, null=True)),
                ('payment_mode', models.CharField(choices=[('net banking', 'Net banking'), ('debit card', 'Debit Card'), ('credit card', 'Credit Card'), ('paytm', 'PayTm')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('designation', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='reporting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Manager'),
        ),
    ]
